# Generated by Django 3.0.3 on 2020-03-01 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0002_auto_20200228_0832'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_field_pref', models.CharField(max_length=100)),
                ('location_pref', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_app.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='File_uploaded',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=60)),
                ('submitted_date', models.DateTimeField()),
                ('comments', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_app.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Employment_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer', models.CharField(blank=True, default='', max_length=150)),
                ('job_function', models.CharField(blank=True, max_length=100)),
                ('current_job_status', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_app.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Education_level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification', models.CharField(max_length=100)),
                ('issuing_org', models.CharField(max_length=100)),
                ('identification_number', models.CharField(max_length=100)),
                ('issue_date', models.DateTimeField()),
                ('expiration_date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_app.Profile')),
            ],
        ),
    ]
