# Generated by Django 3.0.3 on 2020-03-13 07:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0005_auto_20200303_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education_level',
            name='user',
        ),
        migrations.RemoveField(
            model_name='employment_details',
            name='user',
        ),
        migrations.RemoveField(
            model_name='file_uploaded',
            name='user',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='Preference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job_app.Preference'),
        ),
        migrations.AddField(
            model_name='profile',
            name='education_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job_app.Education_level'),
        ),
        migrations.AddField(
            model_name='profile',
            name='employment_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job_app.Employment_details'),
        ),
        migrations.AddField(
            model_name='profile',
            name='file_upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job_app.File_uploaded'),
        ),
        migrations.AlterField(
            model_name='file_uploaded',
            name='submitted_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
