# Generated by Django 3.0.3 on 2020-03-30 15:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0006_auto_20200313_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education_level',
            name='certification',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='education_level',
            name='expiration_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='education_level',
            name='issuing_org',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='preference',
            name='job_field_pref',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='preference',
            name='location_pref',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
