# Generated by Django 3.0.3 on 2020-03-30 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0008_auto_20200330_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employment_details',
            name='current_job_status',
            field=models.CharField(choices=[('not employed', 'Not Employed'), ('employed', ' Employed')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='file_uploaded',
            name='file_name',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
