# Generated by Django 3.0.3 on 2020-04-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0011_auto_20200405_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education_level',
            name='certification',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='education_level',
            name='identification_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='education_level',
            name='issuing_org',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
