# Generated by Django 3.0.3 on 2020-04-06 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0013_auto_20200406_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Preference',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='job_app.Preference'),
        ),
    ]
