# Generated by Django 3.0.3 on 2020-04-06 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0014_auto_20200406_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='education_level',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='job_app.Education_level'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='employment_details',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='job_app.Employment_details'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='file_upload',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='job_app.File_uploaded'),
        ),
    ]
